### ISSUE TITLE
ability to export class names

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#105]
Example:

```css
@export {
  .button {
    color: red;
  }
}
```

test.pc

```html
<import as="something" src="./test.pc">
<div className="@something.button"></div>
```

TODO:

- needs to scan selectors & media queries
