### ISSUE TITLE
ability to export imports

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#118]
E.g:

```html
<import export src="./colors.pc">
<import export src="./typography.pc">
```

Alternatively:

```html
<import export as="colors" src="./colors.pc">
<import export as="typography" src="./typography.pc">
```

This means however that'll need to support deeper references. E.g:

```html
<import as="ds" src="design-system">
<style>
  .style {
    @include ds.typography.font-basic;
  }
</style>
```

`as` may be dropped which would be equivalent to `import * from "./source.pc". For example:

```html
<import export src="./colors.pc" />
```

☝️ Useful for barreling files. 

#### Considerations

- How does this map to a UI?
- Collisions 
- autocomplete (shouldn't be hard since exports are flattened - path is an array)

**Comment by crcn** [comment]
Better yet, just use Sass's syntax:

```css
@mixin desktop {
  @media (min-width: #{$desktop-width}) {
    @content;
  }
}

.rule {
  @include desktop {
    color: red;
  }
}
```
