### ISSUE TITLE
Some way to handle media query breakpoints

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#130]
Possibly another macro for this:

media-queries.pc:

```css
@container media-screen-mobile {
   @media screen and (max-width: 420px) {
      @include children;
   }
}
```

Then in code:

```css
@use-container media-screen-mobile {
   .my-rule {
     color: blue;
   }
}
```

☝🏻 Shooting from the hip, but something _similar_ to this.

**Comment by crcn** [comment]
Better yet, just use Sass's syntax:

```css
@mixin desktop {
  @media (min-width: 100px) {
    @content;
  }
}

.rule {
  @include desktop {
    color: red;
  }
}
```
