### ISSUE TITLE
Ability to nest @media rule in class

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#146]
```css
.rule {
  @media screen and (max-width: 1024px;) {
    color: blue;
  }
}
```
