### ISSUE TITLE
Ability to define @incude outside of style rule

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#147]
For example:

```css
@include media-rule {
  .rule {
    color: blue;
  }
}
```
