### ISSUE TITLE
CSS nesting issue

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#172]
This doesn't work: 

```css

.company_list {
    list-style: none;
    margin: 0;
    padding: 0;

    & li {
      @include large-text;

      display: block;
      padding: var(--spacing-600) 0;

      & + li {
        border-top: 1px solid var(--color-black-100);
      }
    }
  }
```
