### ISSUE TITLE
CSS crashes

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#181]
```css

    @mixin PublicPageBackground {

      background-repeat: repeat;
      background-attachment: fixed;
      background-image: url('/signup/background.png');
      /* stylelint-disable unit-no-unknown */
      background-image: -webkit-image-set(
        url('/signup/background.png') 1x,
        url('/signup/background@2x.png') 2x,
        url('/signup/background@3x.png') 3x
      );
    }
```
