### ISSUE TITLE
pseudoelement not working for tag names

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#182]
```css

  .logo {
    display: flex;
    svg:last-child {
      margin-right: 4px;
    }
  }
```
