### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#326]
Where pseudo selector is:

```css
 @media screen and (max-width: 900px) {
    ._main-features {
      ._item:first-child {
          padding-right: 0;
          border-right: 0;
          padding-left: 0;
          border-left: 0;
        /* &:first-child {
          padding-right: 0;
          border-right: 0;
        } */
        /* &:last-child {
          border-left: 0;
        } */
      }
    }
```
