### ISSUE TITLE
declaration order should be respected

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#481]
E.g:

```css
  @mixin mobile {
    @media screen and (max-width: 900px) {
      @content;
    }
  }

div {
  color: blue;
  @include mobile {
    color: red;
  }
}
```
