### ISSUE TITLE
incorrect transpilation with :self

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#526]
Compiled incorrectly:

```css
:self(.active, :hover) {
            background: blue;
          }
```
