### ISSUE TITLE
& doesn't work in media query mixin

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#529]
```css
.element {
@include theme.desktop-s {
        background: blue;
        width: 50%;
        &:last-child {
          font-size: 24px;
        }
      }
}
```
