### ISSUE TITLE
global styling not working correctly

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#534]
```css
<style>
    display: flex;
    align-items: center;
    padding: 17px 0px;
    :global(._button) {
      && {
        padding: 0px;
        border: none;
      }
    }
  </style>
```
