### ISSUE TITLE
multiple :not not working

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#535]
```css
&:not(:disabled):not(.transparent) {
      &.hover,
      &:hover,
      &:focus {
        cursor: pointer;
        background-color: #E76E69;
        border: 1px solid #E76E69;
        color: #fff;
      }

      &:active,
      &:focus {
        cursor: pointer;
        background-color: #E76E69;
        border: 1px solid #E76E69;
        color: #fff;
      }
    }
```
