### ISSUE TITLE
Can't deeply nest &

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#547]
```css
:self(.v3) {
      &&& {
        width: 16px;
        height: 16px;
        min-width: auto;
        

        /* colorIcon / disabled */
        border: 2px solid #7C7C7C;
        box-sizing: border-box;
        border-radius: 2px;
        
        &:checked {
          border-color: red;
        }

        
      }
    }
```
