### ISSUE TITLE
media query doesn't work within :self(params)

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#573]
see PC website. Code is this:

```css

    :self(:first-child) {
      border-right: 1px solid rgb(226, 226, 226);
      padding-right: 30px;

      @include mobile {
        padding-right: 0px;
        border-right: 0px;
      }
    }
```
