### ISSUE TITLE
:not(:within(.class)) not working

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#607]
```css
<Wrapper component as="Preview"
   className:login="login"
    className:emailCheck="emailCheck">
  <style>
    color: white;
  </style>
  
  <Topbar.Preview2 />

  <!-- Need account top -->
  <Actions>
    <Topnav label="Don't have an account?" link={<a data-testid="log_in:link:dont_have_an_account_signup">Sign up</a>}>
      <style>
        :not(:within(.login)) {
          display: none;
        }
      </style>
    </Topnav>

    <Topnav label="Already have an account?" link={<a data-testid="log_in:link:dont_have_an_account_signup">Sign in</a>}>
      <style>
        :not(:within(.emailCheck)) {
          display: none;
        }
      </style>
    </Topnav>
  </Actions>
```

**Comment by crcn** [comment]
This is actually caused by confusing syntax -- functionality is correct. Solution is to do this: 

```css
&:not(:within(.emailCheck)) {
          display: none;
        }
```

Syntax for `:within` should actually be this:

```css
&:within(.email) {
  color: red;
}
```
