### ISSUE TITLE
nested within not behaving correctly

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#746]
```css
&:within(.slim) {
  &:within(.active) {
    color: red;
  }
}
```

Should be compiled to:

```css
.slim.active [data-pc-element], .slim .active [data-pc-element] {
  color: red;
}
```
