### ISSUE TITLE
css nesting doesn't work with groups

### ISSUE THREAD

**Issue by crcn** [paperclip-ui/legacy-paperclip#84]
For example:

```css
a, b {
  & c {
    color: blue;
  }
}
```

Should be expanded to:

```css
a c, b c {
}
```
